CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id SERIAL PRIMARY KEY NOT NULL, 
  title VARCHAR NOT NULL, 
  userid INTEGER REFERENCES users (id) NOT NULL
);